CZE: Česká Republika
AFG: Afghánistán
ALA: Alandské ostrovy
ALA: Albánie
ALG: Alžírsko
AME: Americká Samoa
US_: Americké Virginské Ostrovy
AGL: Angola
ANG: Anguila
ATA: Antarktida
ANT: Antigua
ARG: Argentina
ARM: Arménie
ARU: Aruba
AUS: Austrálie
BMS: Bahamy
BAH: Bahrajn
BAN: Bangladeš
BAR: Barbados
MYA: Barma
BGM: Belgie
BEL: Belize
BEN: Benin
BER: Bermudy
BTN: Bhútán
BOL: Bolívie
BOS: Bosna a hercegovina
BOT: Botswana
BRA: Brasilia
BRI: Britské Virginské Ostrovy
BRU: Brunej
BUL: Bulharsko
BKF: Burkina Faso
BUR: Burundi
BLR: Bělorusko
COT: Břeh slonoviny
CHL: Chile
CRO: Chorvatsko
COO: Cookovy ostrovy
DOM: Dominika
DRP: Dominikánská Republika
DEN: Dánsko
DJI: Džibutsko
EGY: Egypt
ECU: Ekvádor
ERI: Eritrea
EST: Estonsko
ETH: Etiopie
FAR: Faerské ostrovy
FLK: Falklandy
FIJ: Fidži
PHI: Filipíny
FIN: Finsko
FRA: Francie
FRE: Francouzká Guayana
PYF: Francouzká Polynezie
GAB: Gabon
GAM: Gambie
GHA: Ghana
GIB: Gibraltar
GRE: Grenada
GEO: Gruzia
GRL: Grónsko
GDL: Guadeloupe
GUM: Guam
GUA: Guatemala
GUY: Guayana
GGY: Guernsey
GUI: Guinea
GBS: Guinea-Bissau
HAI: Haiti
NED: Holandsko
HON: Honduras
HKG: Hongkong
IND: Indie
IDS: Indonésie
IRE: Irsko
IRA: Irák
ICE: Island
ITA: Itálie
ISR: Izrael
JAM: Jamajka
JAP: Japonsko
YEM: Jemen
JEY: Jersey
SOU: Jižní Afrika
SGS: Jižní Georgie a Jižní Sandwichovy ostrovy
SKO: Jižní Korea
ATF: Jižní francouzské teritorie
JOR: Jordánsko
CAY: Kajmanské ostrovy
CAM: Kambodža
CMR: Kamerun
CAN: Kanada
CAP: Kapverdské ostrovy
QAT: Katar
KAZ: Kazachstán
KEN: Keňa
KIR: Kiribati
CCK: Kokosové ostrovy
COL: Kolumbie
COM: Komorské ostrovy
CON: Kongo
COD: Konžská Demokratická Republika
COS: Kostarika
CUB: Kuba
KUW: Kuvajt
CYP: Kypr
KYR: Kyrgystán
LAO: Laos
LES: Lesotho
LEB: Libanon
LBY: Libye
LIB: Libérie
LIE: Lichtenštejnsko
LIT: Litva
LAT: Lotyšsko
LUX: Lucenbursko
MAC: Macao
MAD: Madagaskar
MKD: Makedonie = " FYROM
MLW: Malawi
MAL: Maledivy
MLI: Mali
MLS: Malijsie
MLT: Malta
MOR: Maroko
MHL: Marshallovy ostrovy
MAR: Martinik
MRT: Mauretánie
MAU: Mauricius
MYT: Mayotte
HUN: Maďarsko
UMI: Menší odlehlé ostrovy Spojených států
MEX: Mexico
FSM: Mikronésie
MOL: Moldavsko
MCO: Monako
MON: Mongolsko
MTT: Monserat
MOZ: Mosambik
NAM: Namibie
NEP: Nepál
NIG: Niger
NGR: Nigérie
NIC: Nikaragua
NIU: Niue
NET: Nizozemské Antily
NWY: Norsko
CDN: Nová Kaledonie
GER: Německo
OMA: Omán
BVT: Ostrov Bouvet
HMD: Ostrov Heard a McDonaldovy ostrovy
IMN: Ostrov Man
NFK: Ostrov Norfolk
SJM: Ostrov Svalbard a Jan Mayen
TCI: Ostrovy Turks a Caicos
PLW: Palauská republika
PSE: Palestinian territory
PAN: Panama
PAP: Papua-Nová Guinea
PAR: Paraguay
PER: Peru
PCN: Pitcairnovy ostrovy
POL: Polsko
PUE: Portoriko
POR: Portugalsko
PAK: Pákistán
AUT: Rakousko
MNE: Republika Černá hora
REU: Reunion
EQU: Rovníková Guinea
ROM: Rumunsko
RUS: Rusko
RWA: Rwanda
EL_: Salvador
SAN: San Marino
SAU: Saúdiská Arábie
SEN: Senegal
KOR: Severní Korea
SEY: Seychely
SIE: Sierra Leone
SIN: Singapur
SLO: Slovensko
SLV: Slovinsko
SOM: Somálsko
UAE: Spojené Arabské Emiráty
UNI: Spojené státy americké
MNP: Společenství Severních Marian
YUG: Srbská republika
SRI: Srí Lanka
CEN: Středoafrická Republika
SUR: Surinam
SHN: Svatá Helena
SLU: Svatá Lucie
SKN: Svatý Krištof a Nevis
SAO: Svatý Tomáš a Princův ostrov
ST: Svatý Vincenc a Grenadiny
SWA: Svazijsko
SUD: Súdán
SYR: Sýrie
TAN: Tanzanie
WLF: Teritorium ostrovů Wallisa a Futuna
SPM: Teritoriální společenství Saint-Pierre a Miquelon
TWN: Thaj-wan
THA: Thajsko
TLS: Timor-Leste
TOG: Togo
TKL: Tokelau
TON: Tonga
TRI: Trinidad a Tobago
TUN: Tunisko
TUR: Turecko
TKM: Turkmenistán
TUV: Tuvalu
TAJ: Tádžikistán
UGA: Uganda
UKR: Ukrajina
URU: Uruguay
UZB: Uzbekistán
VAN: Vanuatu
VAT: Vatikán – Svatá stolice
GBR: Velká Británie
VEN: Venezuela
VIE: Vietnam
CXR: Vánoční ostrovy
ZAM: Zambie
ZIM: Zimbabwe
ESH: Západní Sahara
WES: Západní Samoa
AZE: Ázerbádžán
IRN: Írán
CHA: Čad
CHN: Čína
GRC: Řecko
SOL: Šalomounovy ostrovy
SPA: Španělsko
SWE: Švédsko
SWI: Švýcarsko
